# Generated by Django 4.0.4 on 2022-05-28 13:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NIDDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.IntegerField()),
                ('is_approved', models.CharField(blank=True, choices=[('accepted', 'Approved'), ('cancel', 'Cancel')], max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NID_Info',
        ),
    ]
