# Generated by Django 4.0.4 on 2022-05-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NIDDB', '0002_applicant_data_delete_nid_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant_data',
            old_name='is_approved',
            new_name='status',
        ),
    ]
