# Generated by Django 4.0.4 on 2022-05-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIDDB', '0003_rename_is_approved_applicant_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_data',
            name='nid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='applicant_data',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Canceled', 'Canceled')], default='Undecided', max_length=255),
        ),
    ]
