# Generated by Django 4.0.4 on 2022-05-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIDDB', '0004_alter_applicant_data_nid_alter_applicant_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_data',
            name='nid',
            field=models.IntegerField(max_length=17, unique=True),
        ),
    ]
