# Generated by Django 4.0.4 on 2022-05-30 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIDDB', '0005_alter_applicant_data_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_data',
            name='nid',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
    ]
